name = "lily-auth"
main = "functions/verify.js"
compatibility_date = "2025-10-25"

[vars]
TURNSTILE_SECRET = "0x4AAAAAAA8msPSSUkWUwMZh4DazG3dpsgE"

[kv_namespaces]
binding = "AUTH_DB"
id = "your_kv_namespace_id_here"