name = "lily-auth"
compatibility_date = "2024-10-01"
pages_build_output_dir = "."

[vars]
ENVIRONMENT = "production"

[build]
command = ""

[kv_namespaces]
binding = "AUTH_DB"
id = "1a667999b70440fe9895a69acd13108a"