name = "lily-auth"
main = "./functions/api/verify.js"
compatibility_date = "2024-10-01"

[site]
bucket = "./"
entry-point = "functions"

[vars]
ENVIRONMENT = "production"

[pages]
build_output_dir = "."

[[kv_namespaces]]
binding = "AUTH_DB"
id = "1a667999b70440fe9895a69acd13108a"