name = "lily_auth"
main = "functions/verify.js"
compatibility_date = "2025-10-25"

[vars]
TURNSTILE_SECRET = "0x4AAAAAAB8msEdkjmlt0lYu2gQicmjkkOQ"

name = "verify-worker"
main = "src/index.js"
compatibility_date = "2025-10-25"

[[kv_namespaces]]
binding = "ARCHIVE_KV"
id = "3036282dbf054154ab68948faa795509"