name = "lily_auth"
main = "src/verify.js"
compatibility_date = "2025-10-25"

[vars]
TURNSTILE_SECRET = "0x4AAAAAAB8msEdkjmlt0lYu2gQicmjkkOQ"

name = "verify-worker"
main = "src/index.js"
compatibility_date = "2025-10-25"

[build.upload]
format = "service-worker"

[[kv_namespaces]]
binding = "ARCHIVE_KV"
id = "3036282dbf054154ab68948faa795509"

[site]
bucket = "./public"

[env.production]
services = [
  { binding = "lily_auth", service = "lily_auth", environment = "production" }
]

[[services]]
binding = "lily_auth"
service = "lily_auth"
environment = "production"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "pages-assets"