name = "lily-auth"
compatibility_date = "2024-10-01"
pages_build_output_dir = "."

[vars]
ENVIRONMENT = "production"

[build]
command = ""
upload_format = "service-worker"

[[kv_namespaces]]
binding = "AUTH_DB"
id = "1a6679997b7440f4e9895a69acd13108a"