name = "lily_auth"
main = "_worker.js"
compatibility_date = "2024-10-01"

pages_build_output_dir = "public"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "__STATIC_CONTENT"
id = "dummy"