name = "lily_auth"
main = "functions/verify.js"
compatibility_date = "2025-10-25"

[[kv_namespaces]]
binding = "AUTH_DB"
id = "1a667999b70440fe9895a69acd13108a"

[vars]
TURNSTILE_SECRET = "0x4AAAAAAB8msEdkjmlt0lYu2gQicmjkkOQ"